name: flutterboilerplate # TODO(You): Replace with you app's name
description: My Flutter Boilerplate # TODO(You): Replace with you app's description
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.8.0
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.19.0
  image_picker: ^1.1.2




dev_dependencies:
  build_runner: ^2.4.6
  # dart run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.1.0
  # dart run change_app_package_name:main <com.new.package.name>
  envied_generator: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  # dart run flutter_launcher_icons:main
  flutter_test:
    sdk: flutter
  #flutter_driver:
  #sdk: flutter
  freezed: ^2.4.5
  very_good_analysis: ^5.1.0
  # screenshots: ^2.1.1
  # screenshots
  # test: any

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
